name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create subfolder
        run: mkdir my-package

      - name: Install UCC
        run: |
          pip install splunk-add-on-ucc-framework
          pip install splunk-packaging-toolkit

      - name: Build an app using UCC
        run: |
          version=$(echo ${{ github.ref_name }} | cut -c 2-)
          ucc-gen build --ta-version $version

      - name: Create tmp folder
        run: mkdir app-dir
      
      - name: Create package
        run: ucc-gen package --path output/devtutorial_conf24 -o app-dir/
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: my-package
          path: app-dir/

  release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: my-package

    - name: Create a Release
      env:
        GH_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
      run: |
        package_name=$(ls -1 *gz | xargs basename)
        gh release create ${{ github.ref_name }} $package_name -F release_notes/${{ github.ref_name }}.md